# Site settings
name: Swathi Bhat
title: Swathi Bhat | Graduate student at UCSB
description: 
url: https://swathisbhat.github.io/
baseurl: ''
email: swathibhat282@gmail.com
cover: https://swathisbhat.github.io/img/og.png
logo: https://swathisbhat.github.io/img/emojis/technologist.png
resume: https://swathisbhat.github.io/resume.pdf
social:
  - title: email
    url: mailto:swathibhat282@gmail.com
  - title: github
    url: https://github.com/SwathiSBhat
  - title: linkedin
    url: https://www.linkedin.com/in/swathi-s-bhat-6180a3128

# Build settings
markdown: kramdown

exclude:
  - 'Gemfile'
  - 'Gemfile.lock'
  - '*.gemspec'
  - 'README.md'
  - 'node_modules'
  - 'build'
  - 'gulpfile.js'
  - 'package.json'

keep_files:
  - 'CNAME'
  - '.git'
  - '.gitignore'

plugins_dir:
  - jekyll-minifier
  - jekyll-sitemap
